### ISSUE TITLE
Make Parquet files for WISE light curves from Meisner et al., 2023

### ISSUE THREAD

**Issue by jkrick** [fornax-navo/fornax-demo-notebooks#105]
Aaron Meisner's WISE light curve catalog is currently in fits format sitting local to Meisner.  @troyraen and I have discussed with him hosting that dataset at IRSA in parquet format. This should speed up the light curve use case by both allowing faster access through parquet format, and putting the catalog 'near' the use case notebook.  The notebook works in its current configuration, but this would be an enhancement to the current notebook.  

Plan if we do want to do the parquet route:
1. Meisner is working on extending the catalogs through WISE year 9 (currently complete to year 7), and expects to be done ~end of summer.
2. Meisner's fits catalog needs to be converted to parquet
3. Parquet catalogs put into the cloud - ideally to be accessible by IRSA SP and SMCE
4. write a tutorial notebook on how to access the parquet files.  Specifically this should include asking to return light curves for a table of N sources, where N ~750K as a first guess.

We can choose to 
a) convert the current (year 7) to parquet and then do it again for the next release.
b) wait for year 9 and then convert to parquet
c) do nothing, the notebook is not broken. 

The benefit of a) is faster access to scaled up version of the light curve notebook, and a test of the system to do the conversion end to end.  However, b) is the most efficient use of time since it means only working on this dataset once, instead of twice.

**Comment by troyraen** [comment]
The files have been created, verified, and uploaded to a testing bucket in S3. We plan to move it to a permanent bucket that is part of the AWS Open Data Program soon. #111 updated the light curve notebook to use the new files.

**Comment by troyraen** [comment]
The current catalog includes data through NEOWISE year 7. We will update the parquet files with new data as soon as the original (FITS) catalog is updated.
