### ISSUE TITLE
Re-evaluate directory structure for code and data files

### ISSUE THREAD

**Issue by troyraen** [fornax-navo/fornax-demo-notebooks#106]
Currently, the data and code used by the forced_photometry notebook is stored in the corresponding subdirectories of the repo's _root_ directory while the light_curves notebook stores in subdirectories of the light_curves directory. Now that we have two examples, we could re-evaluate how we're organizing those files.

**Comment by jkrick** [comment]
Good point, I agree, lets store them in the notebook subdirectories.

**Comment by jkrick** [comment]
@troyraen this is not important or necessary, but when you have the time, can you please re-open a PR with this updated directory structure?  Now is a better time to merge than before the demo.
