### ISSUE TITLE
Speedup WISE_get_lightcurves

### ISSUE THREAD

**Issue by jkrick** [fornax-navo/fornax-demo-notebooks#117]
Suggestions for how to speedup this section:

1. Work with the parquet call:
  - is there a way to vectorize finding which partition an object is in?
  - potentially make a dict or pandas df with hp.query_circle
  - goal is to be able to do a sort of groupby on the coords of the objects
  - This is a general question of how to efficiently search the whole sky for a large list of coords that will benefit other use cases

2. Take all the other things out of the coordinate search
 - flux conversion 
    - make a list of result_table and concatenate that into one object either astropy table or a data frame.

3. Think about weather or not we have a dfsingle.append or collect all the dfsingles and append later 
 - This might already be changed as a ripple effect of the above suggestions.

**Comment by troyraen** [comment]
> * goal is to be able to do a sort of groupby on the coords of the objects

Slight clarification that the goal is to find the partition each coord is in, then groupby the partitions so that we only have to load each partition once and can then find all objects that are in there.

**Comment by jkrick** [comment]
I briefly checked to see if I could tell why pan-starrs search is so much faster than WISE or ZTF, and try to learn from that successful search.  Pan-Starrs search currently is done in a for loop over each object, so not sure why it is so much faster, other than that the pan-starrs API must be faster?
