### ISSUE TITLE
Plotting for the 'TESS, Kepler, K2' dataset might be broken

### ISSUE THREAD

**Issue by jkrick** [fornax-navo/fornax-demo-notebooks#136]
There is a comment in this section of the plotting function saying that it is no longer in use.  I had to edit it to make the new Gaia speedup function work (go figure).  

Since we need to touch the functions which retrieve these lightcurves using lightKurve in the next month, I leave this issue here as a placeholder to remind us (me) to check the plotting at the same time.

**Comment by troyraen** [comment]
There were a couple of bugs that caused these bands to not be plotted in many cases. They are now fixed, and I've removed that comment from the plotting function. I tested a sample of 130 objects and found both TESS and K2 bands, but not Kepler. I assume there was just no Kepler data for those objects (but obviously can't be sure). I think we can close this issue now?

**Comment by jkrick** [comment]
thanks for fixing, good to close.
