### ISSUE TITLE
Document amount of CPU and memory needed to run full notebook at scale

### ISSUE THREAD

**Issue by troyraen** [fornax-navo/fornax-demo-notebooks#137]
We have made significant improvements to several of the archive calls in the light curve notebook. These have been tested individually. The notebook now needs to be tested in full, at scale (500,000 objects) to determine the required resources (number of CPUs and GB memory). Then we should document these numbers, perhaps at the top of the notebook. I think it would also be helpful to list these numbers for some small number (100?) of objects. The notebook cell that calls all the archives in parallel will require the most resources.

**Comment by jkrick** [comment]
In addition, we need some verbiage in the intro section of the code which helps people decide if they should be running the code in the parallel section, or the script.

**Comment by troyraen** [comment]
In testing #215, I was able to obtain the SDSS 500k sample on irsakusp. I did this twice, and it ran smoothly both times.

- Runtimes for each archive were (2nd run):

  ```
  gaia : 73 min (1.2 hr)
  heasarc : 17 min (0.3 hr)
  icecube : 5 min (0.1 hr)
  wise : 279 min (4.7 hr)
  ztf : 456 min (7.6 hr) -- 8 workers
  ```

- CPU load average was about 2.5 (by eye).

- RAM -- I wish I would have paid more attention to this, but I think it needs between 16GB and 32GB.

- Disk-space used by each archive's parquet file containing it's light curve data:

  ```
  448M    lightcurves.parquet/mission=gaia
  209K    lightcurves.parquet/mission=heasarc
  6.0M    lightcurves.parquet/mission=icecube
  199M    lightcurves.parquet/mission=wise
  6.6G    lightcurves.parquet/mission=ztf
  7.2G    total
  ```

**Comment by troyraen** [comment]
I've tested on the SMCE, and ran into at least two problems with larger sample sizes:

1. There is not enough disk space to write the light curves to parquet files. My (home?) directory can only hold 4GB total. (For SDSS 500k, ZTF parquet alone is 6.6GB.) This is the major blocker.

2. `top` can be misleading and show more total RAM than is actually allotted. E.g., a machine with 4G/4CPU shows: `GiB Mem :     15.3 total`. I'm guessing this is because it allows bursting, but eventually kills your job if it uses more than allotted for too long. This can lead one to believe that the job is within resource limits when it's actually not. This is not a major blocker, just something to be aware of.

**Comment by troyraen** [comment]
The scale_up.md notebook added by #215 has a section showing how to determine the CPU and RAM usage and demonstrates using the SDSS 500k sample. So I think this issue can be closed when that merges.

**Comment by troyraen** [comment]
I will also add a line to the light_curve_generator and scale_up notebooks stating the amount of CPU and RAM needed to run each notebook as-is (i.e., using the Yang sample).

**Comment by troyraen** [comment]
Completed by #215
