### ISSUE TITLE
File paths are specific to one user

### ISSUE THREAD

**Issue by stargaser** [fornax-navo/fornax-demo-notebooks#16]
File paths are specific to user `jkrick`, starting with `/home/jkrick`. These could be replaced with `/home/jovian` or perhaps better, made into relative paths from the notebook directory.

**Comment by bsipocz** [comment]
👍 to work with relative paths, that would ensure all things would work more seamlessly when cloned into a different platform whether it's the IRSA one or TIKE or the MCE.
(another option is to rely on env variables like `$HOME`, but that would not address the cross platform related issues).

**Comment by jkrick** [comment]
good points, thanks for finding this.  I'll fix in next branch.
