### ISSUE TITLE
Revise dependencies of notebooks

### ISSUE THREAD

**Issue by bsipocz** [fornax-navo/fornax-demo-notebooks#184]
We have the requirement.txt files, e.g. https://github.com/fornax-navo/fornax-demo-notebooks/blob/main/light_curves/requirements-lc_classifier.txt, but these are not up-to date with the actual requirements. 

Notebooks may still work if dependencies are available through the default container on the platform they are run, but IMO it would be nice to be explicit and list things that we eventually directly import.

E.g. `numba` comes to mind, it's used in [light_curves/code_src/ML_utils.py](https://github.com/fornax-navo/fornax-demo-notebooks/blob/5deb97cc7d59188589ed64e1abd631f1fd7b5742/light_curves/code_src/ML_utils.py#L2), but haven't mentioned anywhere as a dependency. There maybe other examples, too.

**Comment by jkrick** [comment]
Are you suggesting we document which dependencies are there for the cases where they are not explicitly pip installed?  or what are you suggesting we actually do?  I thought the goal was to make the software in the container be the complete list of what we needed.

**Comment by bsipocz** [comment]
I would suggest to list everything we directly use in `requirements.txt` independently whether they are installed on the SMCE or not:

- some of the notebooks will be useful outside the platform, or at least as a removal of some of the "black-box" feelings about the platform and the images available
- there will be multiple images, one may open it in a different one
- the requirement file can be used for creating the image itself, or at least as a double check that we do have everything available
- in practice we already do this, e.g even `numpy` is listed in the requirements, so I assume not listing `numba` is just an oversight
-
