### ISSUE TITLE
Having a config system to pick small sample or full

### ISSUE THREAD

**Issue by bsipocz** [fornax-navo/fornax-demo-notebooks#200]
This is just brainstorming:

We may want to use some configs somewhere to an easy switch between full notebooks and testing? 
That way there is only one version of the notebooks themselves and the rendering/testing/etc will pick what's most reasonable for them.

Or one other idea: have a script that search/replace the sample size parts, so e.g. it's only in the testing where the limited sample is run, but the notebooks still default to full samples. 
I suppose no matter which approach we choose, none of these will work for the ML ones where a reasonably sizeable sample is needed for training (though a dummy, small sample may still serve as testing whether the commands still execute, but not necessarily whether the results resembles anything reasonable).

**Comment by jkrick** [comment]
I actually think it does make sense to have the notebooks only work with a small sample, at least for the light curves and forced photometry, and what will be the spectroscopy use cases.  This lets the user be able to quickly click through and run the notebook as is.  As a user I find this useful as I am trying to understand something to be able to run it.  

So I think we should try to make the use cases run in a "short" amount of time, and then leave comments about how long it might take if we were to run a larger sample/area as well as a commented out example of how to do that.

I am willing to hear counterpoints....

And still thinking about what this means for the ML notebooks.  I think they should also run quickly, maybe that means different parameters, or also commented out calls to hyper parameter searches.   Not sure yet, could also be the config file idea above.

**Comment by bsipocz** [comment]
> So I think we should try to make the use cases run in a "short" amount of time, and then leave comments about how long it might take if we were to run a larger sample/area as well as a commented out example of how to do that.

Ok. I think this indeed makes sense from the users' POV, too, so I'm closing this now.
