### ISSUE TITLE
Bug: Light curves containing NaN are not plotted

### ISSUE THREAD

**Issue by troyraen** [fornax-navo/fornax-demo-notebooks#203]
When a (single band) light curve contains at least one NaN none of its data points are plotted. For example, see SDSS (object 2, band "TESS") or (object 35, band "K2").

This is happening because `scipy.stats.zscore` "propagates" NaN by default. To ignore NaNs instead, the kwarg `nan_policy='omit'` can be used (see [scipy.stats.zscore](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.zscore.html)).

Another option would be to remove NaNs from the dataframe before calculating the zscore.

**Comment by jkrick** [comment]
I like the idea of dropping NaN's from the data frame before plotting.  Can that go in the new` _clean_lightcurves` before the `zscore` gets calculated?

sorry I read this after the PR with all the plotting, but I do think it would make sense to take care of this in that same PR #199 , so I'll copy this comment over there.

**Comment by troyraen** [comment]
> I like the idea of dropping NaN's from the data frame before plotting. Can that go in the new `_clean_lightcurves` before the `zscore` gets calculated?

Yes, done. But also, I wonder if these should not be in the dataframe to begin with? In other words, maybe each archive call/function should drop rows containing NaN before returning their results. Are those rows actually useful at any point?

**Comment by jkrick** [comment]
I can't think of a case where we need a NaN.  Mabe it is useful at some level to know that an archive call worked???  I'll take your recommendation on where the NaN dropping should get done, but I am find with it happening at the plotting stage.  It's easier at this point to not go back into every archive call function.

**Comment by troyraen** [comment]
> I'll take your recommendation on where the NaN dropping should get done

I think this is really a science question. I suppose I could be useful at some point to just know that an observation was taken even if it didn't result in good data.

**Comment by troyraen** [comment]
In that case, we can call this done now.
