### ISSUE TITLE
Bug: Gaia returning HTTP 500 "Cannot process request" 

### ISSUE THREAD

**Issue by troyraen** [fornax-navo/fornax-demo-notebooks#216]
Capturing an error I keep encountering from Gaia. I have not investigated further.

```
traen@jupyter-traen:/home/jovyan/fdn-tmp/light_curves$ cat output/lightcurves-shooby/logs/gaia.log 
Building lightcurves from gaia mission.
INFO: Query finished. [astroquery.utils.tap.core]
500 Error 500:
Code: -1, msg: Impossible to format the query result: no formatter has been found for the given MIME type "votable_gzip"

Cannot process request: 'https://gea.esac.esa.int/data-server/data' (req: Reqid: anonymous1706309619337, retrieval access: DIRECT, retrieval type: EPOCH_PHOTOMETRY, compression: null), for user: UwsJobOwner{id='anonymous', name='null', mail='null', authUsername='null', authGroups=[], pseudo='anonymous', session='1B6CF2BF3703D2DF0E75E08510F2D75B', ip='134.4.70.45', roles=0, parameters=Owner parameters: 6},  due to: Code: -1, msg: Impossible to format the query result: no formatter has been found for the given MIME type "votable_gzip"
Traceback (most recent call last):
  File "/home/jovyan/fdn-tmp/light_curves/code_src/run_light_curve_generator.py", line 227, in <module>
    run(sys.argv[1:])
  File "/home/jovyan/fdn-tmp/light_curves/code_src/run_light_curve_generator.py", line 219, in run
    _ = _build_lightcurves(
        ^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/fdn-tmp/light_curves/code_src/run_light_curve_generator.py", line 101, in _build_lightcurves
    lightcurve_df = Gaia_get_lightcurve(sample_table, arcsec.to_value("deg"), verbose)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/fdn-tmp/light_curves/code_src/gaia_functions.py", line 45, in Gaia_get_lightcurve
    gaia_df = Gaia_retrieve_epoch_photometry(gaia_table)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/fdn-tmp/light_curves/code_src/gaia_functions.py", line 149, in Gaia_retrieve_epoch_photometry
    datalink = Gaia.load_data(ids=chunk,
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/astroquery/gaia/core.py", line 302, in load_data
    raise err
  File "/opt/conda/lib/python3.11/site-packages/astroquery/gaia/core.py", line 297, in load_data
    self.__gaiadata.load_data(params_dict=params_dict,
  File "/opt/conda/lib/python3.11/site-packages/astroquery/utils/tap/core.py", line 868, in load_data
    connHandler.check_launch_response_status(response,
  File "/opt/conda/lib/python3.11/site-packages/astroquery/utils/tap/conn/tapconn.py", line 672, in check_launch_response_status
    raise requests.exceptions.HTTPError(errMsg)
requests.exceptions.HTTPError: Error 500:
Code: -1, msg: Impossible to format the query result: no formatter has been found for the given MIME type "votable_gzip"

Cannot process request: 'https://gea.esac.esa.int/data-server/data' (req: Reqid: anonymous1706309619337, retrieval access: DIRECT, retrieval type: EPOCH_PHOTOMETRY, compression: null), for user: UwsJobOwner{id='anonymous', name='null', mail='null', authUsername='null', authGroups=[], pseudo='anonymous', session='1B6CF2BF3703D2DF0E75E08510F2D75B', ip='134.4.70.45', roles=0, parameters=Owner parameters: 6},  due to: Code: -1, msg: Impossible to format the query result: no formatter has been found for the given MIME type "votable_gzip"
```

**Comment by bsipocz** [comment]
What's the astroquery version? I have merged a couple of gaia fixing PRs recently, this maybe a side-effect, or may be fixed by them.

**Comment by bsipocz** [comment]
(The PR was due to upstream changes on the ESA side, so I would be very concerned if you see this with the latest dev version picked up from pypi, but would not be surprised at all to see this with something older than 3 weeks)

**Comment by troyraen** [comment]
```
$ pip freeze | grep astroquery
astroquery==0.4.7.dev9069
```

**Comment by bsipocz** [comment]
@troyraen - could you please copy-paste the code that generates this error, too so we can propagate the problem upstream.

cc @cosmoJFH and @jespinosaar in case you have any insight into what's going on. I've released the version number above this morning.

**Comment by troyraen** [comment]
Thanks! Here is the last line of our code that runs ("line 149" referenced in error msg above). I substituted in the actual kwarg values where I could.

```
from astroquery.gaia import Gaia

datalink = Gaia.load_data(
    ids=chunk,  # list of gaia source_id
    data_release="Gaia DR3",
    retrieval_type="EPOCH_PHOTOMETRY",
    data_structure="COMBINED",
    verbose=False,
    output_file=None,
    overwrite_output_file=True,
)
```

**Comment by troyraen** [comment]
If you want to look at the code, line 149 is here:

https://github.com/fornax-navo/fornax-demo-notebooks/blob/276b2604294d61cd0db4cda1ed986b19ef2923d3/light_curves/code_src/gaia_functions.py#L149

**Comment by cosmoJFH** [comment]
Hi @troyraen, thanks for your feedback. We are aware of this "issue" that will be solved in February/March with the new release of the software in the gaia archive. This is due to the upgrade of the TAP version.

Meanwhile you have to define the parameter format="votable" in your query.

datalink = gaia.load_data(
    ids=4583627001381815936,  # list of gaia source_id
    data_release="Gaia DR3",
    retrieval_type="EPOCH_PHOTOMETRY",
    data_structure="COMBINED",
    verbose=False,
    output_file=None,
    overwrite_output_file=True,
    format="votable"
)

Sorry for any inconvenience. Let me know if this fixed your issue.

**Comment by bsipocz** [comment]
Thanks @cosmoJFH! I wonder how/why this didn't pop up in the astroquery test suite?

**Comment by troyraen** [comment]
That fix seems to be working for us. I'll close this issue when I merge the fix. Thanks!

**Comment by cosmoJFH** [comment]
> Thanks @cosmoJFH! I wonder how/why this didn't pop up in the astroquery test suite?

This issue is not located in astroquery but in the gaia archive. This can only be detected if you try to download  ancillary data from the archive. All the tests that check the functionality of the function _load_data_ make use of a mocked tap connection handler.

**Comment by jespinosaar** [comment]
Hi all, maybe we can improve the remote tests on this module, in order to avoid these kind of issues.
