### ISSUE TITLE
re-work remove_objects_without_W1 function

### ISSUE THREAD

**Issue by jkrick** [fornax-navo/fornax-demo-notebooks#224]
- probably don't want to explicitly copy the df for RAM issue
- probably don't want a for loop for speed issues.
- is it possible to incorporate the remove_incomplete_data function to make this one broader function?

**Comment by troyraen** [comment]
I can see the value of `sigmaclip_lightcurves` being its own function. But I wonder if everything else in sec 2.3 can go into one function, including stuff currently outside of any function like `dropna`. If the order of operations really matters, the new function could call `sigmaclip_lightcurves` at the right time (and then the notebook just calls the new function).

**Comment by jkrick** [comment]
I don't want to put everything inside of one function for two reasons:
1) one function makes it look like it is an easy step.  I want to keep all those things in there to get across the point that the hard work in ML is data prep.  
2) It also keeps the process more transparent, since the things I do up front will either prevent the ML algorithms from working or effect the results.

Somewhere between the current 10 steps and 1 function is the right balance.
