### ISSUE TITLE
Clarify success/failure messages when downloading data

### ISSUE THREAD

**Issue by troyraen** [fornax-navo/fornax-demo-notebooks#52]
Currently, the cells that call `fornax_download`, `Observations.download_products`, and `Observations.download_file` output several warnings, highlighted in red (on fornaxdev). It is not immediately clear whether the downloads succeeded. After reading through the log messages, it seems that they did and everything is fine. 

I think it would be helpful to set the user's expectations and clearly state the result. Specifically:

- [ ] Add some text in or before those cells telling the user which warnings they can expect under normal circumstances.
- [ ] Print a clear success or failure message as the last thing that these cells output.

**Comment by bsipocz** [comment]
The current state of the download is very much reflects its dev status, I expect most of those warnings and prints week go away as we move things upstream. 
Nevertheless, I'll look into it what else can be easily tune down

**Comment by troyraen** [comment]
We've decided not to refactor the multiband-photometry notebook any further, but will continue refining our processes for notebooks going forward.
