### ISSUE TITLE
Refactor `ra` and `dec` -> `SkyCoord`

### ISSUE THREAD

**Issue by troyraen** [fornax-navo/fornax-demo-notebooks#55]
I think it would be nice if this would understand `SkyCoord` coordinates. But in that case these would be one positional arg rather than two.

_Originally posted by @bsipocz in https://github.com/fornax-navo/fornax-demo-notebooks/pull/49#discussion_r971176318_

**Comment by jkrick** [comment]
For my two cents.  SkyCoord I know is supposed to make things easier so that units come along with their values, but I personally find it difficult to use.  I'm not opposed, just throwing that out there.

**Comment by bsipocz** [comment]
It's not just about units, but also the out of box coordinate conversions. No need to do spherical geometry on the fly, but less than a one liner for doing coordinate system conversions, too.
So, I think we should address the pain points of using it? 
(that being said, if we will using a lot of input arrays coming from dataframes, we may not want to go with the skycoord route, as I think pandas won't natively support skycoords)

**Comment by troyraen** [comment]
We've decided not to refactor the multiband-photometry notebook any further, but will consider using `SkyCoord` in notebooks going forward.

> So, I think we should address the pain points of using it?

@jkrick if there are particular pain points that you want to elaborate on maybe we can come up with solutions, or at least something to make it less painful. I'm closing this issue, but that doesn't prevent us from discussing it further right here. Alternately, we could discuss over Slack or Zoom.
