### ISSUE TITLE
Fix imports in light curve notebook

### ISSUE THREAD

**Issue by troyraen** [fornax-navo/fornax-demo-notebooks#96]
Documenting some install/import issues that came up when trying to run the first cell of the multiband_lc.ipynb notebook in a clean environment (conda env + repo dir).

## Meisner et al.

Current code:

```python
try:
    from unTimely_Catalog_tools import unTimelyCatalogExplorer
except ImportError:
    if not os.path.exists('./unTimely_Catalog_explorer'):
        !git clone https://github.com/fkiwy/unTimely_Catalog_explorer.git
    sys.path.append('./unTimely_Catalog_explorer')
    from unTimely_Catalog_tools import unTimelyCatalogExplorer
```

Suggestions:

- append to the system path before trying to import the first time. otherwise I think the first call will (almost) never succeed.
- remove the directory `light_curves/unTimely_Catalog_explorer` from the repo (its presence causes the 4th line to always return false, so `git clone` never gets executed).
- this seems to require the package `reproject`. maybe should just `pip install` it right after `git clone`.

## Alerce

Current code:

```python
!pip install alerce
```

Suggestion:

- treat this like the others using a `try/except`. no need to run the install every time

**Comment by troyraen** [comment]
@bsipocz was working on refactoring a lot of that cell, though I'm not sure whether her scope will cover these issues. If it doesn't, we should revisit some of these after her changes go through because they might affect the best way to handle these.

@jkrick, not thinking about Brigitta's changes for a minute, I think I'd do Meisner like this:

```python
sys.path.append('./unTimely_Catalog_explorer')
try:
    from unTimely_Catalog_tools import unTimelyCatalogExplorer
except ImportError:
    !git clone https://github.com/fkiwy/unTimely_Catalog_explorer.git
    !pip install reproject  # could go in a requirements.txt file
    from unTimely_Catalog_tools import unTimelyCatalogExplorer
```

Generally, a `try` statement should be as short as possible, only containing the line(s) of code that you actually want to try -- i.e., the one(s) that can trigger the error(s) caught by `except`. I think we can skip the check for an existing directory as well. If the repo has already been cloned the first import statement should work, but if it doesn't the `except` block will fail as well (with or without the check). The user will have to manually delete the directory and try again (re-clone it). Checking for the directory doesn't really gain anything and has the potential to hide the problem from the user by suppressing helpful error messages.

I prefer a requirements.txt file to the `try/except` statements. Though in the forced photometry use case I see that we're running `pip install` every time, which the same non-ideal situation I was trying to avoid with the `try/except` suggestion. But unless Brigitta has other suggestions, I think I'd go with the same strategy as the forced photometry notebook. It makes the notebook simpler and is a standard (at least outside of notebook environments... I'm still trying to learn what's standard here) way to manage requirements. And I suppose it's easy to just skip that cell if you know you've already installed everything.

**Comment by bsipocz** [comment]
> !git clone https://github.com/fkiwy/unTimely_Catalog_explorer.git

nitpick: could one not install this as a package? pip could also install it directly from the github link, then no need to add anything to the path and clone and such.

**Comment by bsipocz** [comment]
For very long notebooks like this, I would suggest to actually not do all the imports upfront. Do all generic, and data access related ones at the top, and the ones like these, as well as all the ML could/should come later. That way the notebook is more modular and is not really bogged down on in the first cell with exotic installations.

**Comment by troyraen** [comment]
I'm also noticing many imports which are not actually used in the notebook itself, so they can just be removed. If they are used within a module/file, they should be imported at the top of that file.

**Comment by troyraen** [comment]
I'm having trouble with a fresh install of unTimely. I have to clone it and then restart the kernel before the module can be found. The [repo's instructions](https://github.com/fkiwy/unTimely_Catalog_explorer#installation) are:

```
git clone https://github.com/fkiwy/unTimely_Catalog_explorer.git
cd unTimely_Catalog_explorer
python setup.py install
```

We are not doing the setup step, and I'm not sure of the best way to execute that command within a notebook. The package does not appear to be available on PyPI.

**Comment by troyraen** [comment]
> pip could also install it directly from the github link

This sounds like a great option, but isn't working for me. I get this error:

```
Collecting https://github.com/fkiwy/unTimely_Catalog_explorer.git
  Downloading https://github.com/fkiwy/unTimely_Catalog_explorer.git
     | 281.4 kB 1.2 MB/s 0:00:000m
  ERROR: Cannot unpack file /tmp/pip-unpack-bjbghnc6/unTimely_Catalog_explorer.git (downloaded from /tmp/pip-req-build-k97fro26, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-k97fro26
```

**Comment by bsipocz** [comment]
It works for me with `pip install git+https://github.com/fkiwy/unTimely_Catalog_explorer`, though I haven't tried using it beyond a simple import

**Comment by troyraen** [comment]
> `pip install git+https://github.com/fkiwy/unTimely_Catalog_explorer`

Ah that works, thanks @bsipocz ! I had the wrong syntax.

**Comment by jkrick** [comment]
Just clarifying what I think still needs to be done on this issue so it doesn't get lost.  
1) use namespaces for the local code imports, and change the name of the 'code' directory to a word not protected by python. @bsipocz will you please still do this PR?
2) put all the pip installs in a requirements.txt file, and make a separate cell to call that, as in the forced photometry notebook.
